# PostgreSQL. Versions 7.4 and 8.x are supported.
#

development:
  adapter: postgresql
  encoding: unicode
  database: swapto_development
  pool: 5
  username: swapto
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: swapto_test
  pool: 5
  username: swapto
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: swapto_staging
  pool: 5
  username: swapto
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: swapto_production
  pool: 5
  username: swapto
  password:
